region                     = "ap-northeast-2"
remote_state_bucket        = "donggil-terraform-state"
remote_vpc_state_key       = "vpc/terraform.tfstate"
remote_security_group_key  = "security-group/terraform.tfstate"
remote_secrets_manager_key = "secrets-manager/terraform.tfstate"