apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: buyer-auth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: buyer-auth
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buyer-auth
    spec:
      containers:
      - image: 495523830808.dkr.ecr.ap-northeast-2.amazonaws.com/eks-workshop-buyer-auth:v1.0.9
        imagePullPolicy: Always
        name: buyer-auth
        ports:
        - containerPort: 2020
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-buyer-auth
spec:
  ports:
    - port: 2020
      targetPort: 2020
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: buyer-auth