apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: order
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
    spec:
      containers:
      - image: 495523830808.dkr.ecr.ap-northeast-2.amazonaws.com/eks-workshop-order:v1.1.1
        imagePullPolicy: Always
        name: order
        ports:
        - containerPort: 4040
        resources:
          limits:
            memory: "512Mi"
            cpu: "256m"
          requests:
            memory: "512Mi"
            cpu: "256m"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
          port: 4040
          initialDelaySeconds: 45
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 2
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
          port: 4040
          initialDelaySeconds: 45
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 2
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-order
spec:
  ports:
    - port: 4040
      targetPort: 4040
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: order
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50