apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: product
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: product
    spec:
      containers:
      - image: 495523830808.dkr.ecr.ap-northeast-2.amazonaws.com/eks-workshop-product:v1.1.1
        imagePullPolicy: Always
        name: product
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-product
spec:
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: product