apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: buyer-auth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: buyer-auth
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: buyer-auth
    spec:
      containers:
      - image:  {{ .Values.buyer.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: buyer-auth
        ports:
        - containerPort: 2020
        resources:
          limits:
            memory: "512Mi"
            cpu: "256m"
          requests:
            memory: "512Mi"
            cpu: "256m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-buyer-auth
spec:
  ports:
    - port: 2020
      targetPort: 2020
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: buyer-auth