apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: product
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: product
    spec:
      containers:
      - image: {{ .Values.product.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: product
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-product
spec:
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: product