apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: product
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: product
  replicas: {{ .Values.product.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: product
    spec:
      containers:
      - image: {{ .Values.product.image }}:{{ .Values.version }}
        imagePullPolicy: Always
        name: product
        ports:
        - containerPort: 3030
        resources:
          limits:
            memory: "800Mi"
            cpu: "400m"
          requests:
            memory: "800Mi"
            cpu: "400m"
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 3030
          initialDelaySeconds: 45
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 2
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 3030
          initialDelaySeconds: 45
          periodSeconds: 3
          timeoutSeconds: 2
          failureThreshold: 2
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-product
spec:
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: product