apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: seller-auth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: seller-auth
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: seller-auth
    spec:
      containers:
      - image: 495523830808.dkr.ecr.ap-northeast-2.amazonaws.com/eks-workshop-seller-auth:v1.0.6
        imagePullPolicy: Always
        name: seller-auth
        ports:
        - containerPort: 1010
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-seller-auth
spec:
  ports:
    - port: 1010
      targetPort: 1010
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: seller-auth