apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eks-workshop
  name: order
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: order
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
    spec:
      containers:
      - image: 502697621694.dkr.ecr.ap-northeast-2.amazonaws.com/eks-workshop-order:v1.0.4
        imagePullPolicy: Always
        name: order
        ports:
        - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  namespace: eks-workshop
  name: service-order
spec:
  ports:
    - port: 4040
      targetPort: 4040
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: order