--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-workshop
  region: ap-northeast-2

vpc:
  subnets:
    private:
      ap-northeast-2a: 
        id: subnet-0ab9b882ac1f6f9ae
      ap-northeast-2b: 
        id: subnet-06b1f10cd814f451e
      ap-northeast-2c: 
        id: subnet-0bfe2f96a42319147

nodeGroups:
  - name: ng-workers
    instanceType: t3.micro
    desiredCapacity: 2
    privateNetworking: true